### ISSUE TITLE
Add support for `source` and `source_sha256` in buildpack.toml

### ISSUE THREAD

**Issue by TisVictress** [paketo-buildpacks/pipeline-builder#111]
We're using [Norsk](https://norsk.cf-app.com/teams/norsk-viewers/pipelines/tanzu-dotnetframework-buildpack) to manage open source licensing in the Tanzu dotnet-framework buildpack and it relies on having `source` and `source_sha256` for each buildpack dependency. This is a feature request to retrieve the link to the dependency's source code (.tar.gz), generate its SHA256 value and copy them into the `buildpack.toml` file.

This is low priority since we are able to do this manually but it's a nice-to-have. An example of what we're looking for can be found [here](https://github.com/pivotal-cf/tanzu-dotnet-framework/commit/8de520bcfca299983ff75eb8ea8228fe6ea65b8e).

**Comment by nebhale** [comment]
@TisVictress Thanks for your first contribution!  This feature will require a number of moving pieces to get completed end to end.

- [ ] [GitHub Action](https://github.com/paketo-buildpacks/pipeline-builder#github-release-dependency) emits `source` and `source_sha256`
- [ ] [`update-buildpack-dependency`](https://github.com/paketo-buildpacks/libpak/blob/main/cmd/update-buildpack-dependency/main.go) accepts `source-uri` and `source-sha256`
- [ ] [pipeline](https://github.com/paketo-buildpacks/pipeline-builder/blob/main/octo/update-buildpack-dependency.sh#L11) passes values

**Comment by anthonydahanne** [comment]
this task has been completed on all the buildpacks that could include sources.

Some of them could not:
* buildpacks relying on proprietary dependencies; obviously the code source can't be included since it's not public
* Azul buildpack: they use a manual process to ask for sources; we won't be able to script that! see https://github.com/zulu-openjdk/zulu-openjdk/issues/237 for more details
* Foojay buildpacks (for example, microsoft-openjdk): they don't include the sources in their API; see: https://github.com/foojayio/discoapi/issues/89
